###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.8"
services:

  db:
    image: mysql:8.0
    container_name: ${CONTAINER_MYSQL_NAME}
    restart: unless-stopped
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: rabbit
    ports:
      - ${MYSQL_PORT_IN}:${MYSQL_PORT_OUT}

  nginx:
    build: docker/nginx
    container_name: ${CONTAINER_NGINX_NAME}
    working_dir: /application
    restart: always
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT_IN_80}:${NGINX_PORT_OUT_80}

  app:
    build: docker/php-fpm
    container_name: ${CONTAINER_PHP_FPM_NAME}
    restart: unless-stopped
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
